Resolved SonarQube issues & warnings.
DEFRA/epr-pom-func-submission-check-splitter pull request #10
Opened 2024-08-05 14:21 UTC by davidtonthat

Resolved SonarQube v10.4 issues & warnings.

2024-08-06 08:12 UTC, Mazar-Shaik submitted a review, later dismissed
@davidtonthat LGTM

2024-08-07 15:17 UTC, hardik-desai-kcl approved these changes

2024-08-08 14:43 UTC, hardik-desai-kcl submitted a review, later dismissed

2024-08-08 14:46 UTC, Mazar-Shaik approved these changes

2024-08-19 11:07 UTC, hardik-desai-kcl requested changes
one security issue to be fixed
<img width="1585" alt="image" src="https://github.com/user-attachments/assets/37c0c45e-739e-489c-8e1a-481c755b8cc7">

2024-08-19 12:23 UTC, Mazar-Shaik approved these changes

2024-08-20 09:15 UTC, hardik-desai-kcl approved these changes

2024-08-20 13:30 UTC, EvidenPete approved these changes

2024-08-27 08:41 UTC, merged